pipeline {

    agent {
        docker {
          image 'python:slim'
        }
    }

    stages {
        stage('build') {
          when{
            changeset "**/vote/**"
          }
            steps {
                echo 'Compiling vote app'
                dir('vote'){
                  sh 'pip install -r requirements.txt'
                  }
            }
        }

        stage('test') {
            when{
              changeset "**/vote/**"
            }
            steps {
                echo 'Running Unit Tests on vote app'
                dir('vote'){
                  sh 'nosetests -v'
                  }
            }
        }

    }

    post {
        always {
            echo 'Pipeline for vote app is complete'
        }
        failure {
            slackSend (channel: "testing", message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
        success {
            slackSend (channel: "testing", message: "Build Succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
    }
}
